### ISSUE TITLE
等wepy上了2.0版本我就来一波更新

### ISSUE THREAD

**Issue by brucx** [brucx/wepy-zanui-demo#19]
最近没有写小程序，都在忙着写后台，等wepy上了2.0，就把zanui更新到3.0 😂

**Comment by anonymous-qsh** [comment]
期待着作者大大的更新😂

**Comment by luotingv1** [comment]
期待着作者大大的更新

**Comment by Kaaden** [comment]
想知道什么时候更新2.0

**Comment by jswxwxf** [comment]
大大能不能提前更新一下哈，现在的版本大都用的 px，不是rpx，微信小程序现在开始支持 iPad 了， px 在 iPad 上全乱了啊~~~
